"""empty message

Revision ID: a892c46ca586
Revises: 
Create Date: 2022-05-25 07:47:21.526761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a892c46ca586'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('our_ref', sa.Text(), nullable=True),
    sa.Column('pay_date', sa.Text(), nullable=True),
    sa.Column('req_name', sa.Text(), nullable=True),
    sa.Column('cus_name', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('number', sa.Text(), nullable=True),
    sa.Column('q_date', sa.Text(), nullable=True),
    sa.Column('q_d_date', sa.Text(), nullable=True),
    sa.Column('d_d_date', sa.Text(), nullable=True),
    sa.Column('d_d_num', sa.Text(), nullable=True),
    sa.Column('p_name', sa.Text(), nullable=True),
    sa.Column('charge_01', sa.Text(), nullable=True),
    sa.Column('charge_02', sa.Text(), nullable=True),
    sa.Column('p_charge', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('our_ref')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('question')
    # ### end Alembic commands ###
